services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    depends_on:
      - postgres
    build: .
    ports:
      - 5000:5000
    env_file:
      - docker.env
    
volumes:
  postgres-volume:
